blank_issues_enabled: false

contact_links:
  - name: '🙏 Help'
    url: https://github.com/duncanmcclean/static-cache-manager/discussions/new
    about: 'Have a question? Need help troubleshooting? Open a discussion.'
  - name: '💡 Feature Requests'
    url: https://github.com/duncanmcclean/static-cache-manager/discussions/new
    about: 'Have any idea for a new feature or enhancements to an existing one? Open a discussion.'
